kumuluzee:
  name: event-service
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
#      hosts: http://etcd:2379
  server:
    base-url: http://localhost:8081
    http:
      port: 8081

  datasources:
# DEVELOPMENT
    - jndi-name: jdbc/EventCatalogDS
      connection-url: jdbc:postgresql://localhost:5432/event-catalog
      username: postgres
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/EventCatalogDS
      http-health-check:
        - connection-url: http://github.com/kumuluz/kumuluzee-health
  metrics:
    web-instrumentation:
      - name: event-endpoint
        url-pattern: /v1/catalog/events/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="comments">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="852bac38-fc96-4293-8c3c-78c39d020464-ls.logit.io"
                                port="29177" protocol="udp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info" />
                                    <AppenderRef ref="logstash" level="trace" />
                                </Root>
                            </Loggers>
                        </Configuration>'

  persistence-units:
    - name: "event-catalog-jpa"
      continue-on-error: false

location:
  service-name: location-processing
  port: 8083
  version: 1.0.0
  environment: dev
  process-base-uri: v1/location/process

image:
  service-name: image-upload
  port: 8082
  version: 1.0.0
  environment: dev
  upload-base-uri: v1/upload/


