kumuluzee:
  name: event-service
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379

  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
#    - jndi-name: jdbc/EventCatalogDS
#      connection-url: jdbc:postgresql://localhost:5432/event-catalog
#      username: postgres
#      password: postgres
    - jndi-name: jdbc/EventCatalogDS
      connection-url: jdbc:postgresql:///rsodatabase?cloudSqlInstance=a1-projekat:us-central1:rsodatabase&socketFactory=com.google.cloud.sql.postgres.SocketFactory
      username: postgres1
      password: postgres

  persistence-units:
    - name: "event-catalog-jpa"
      continue-on-error: false

location:
  service-name: location-processing
  port: 8083
  version: 1.0.0
  environment: dev
  process-base-uri: v1/location/process

image:
  service-name: image-upload
  port: 8082
  version: 1.0.0
  environment: dev
  upload-base-uri: v1/upload/


