apiVersion: apps/v1
kind: Deployment
# Name of the deployment
metadata:
  name: event-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-catalog
  template:
    metadata:
      labels:
        app: event-catalog
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: pubsub-key
      containers:
        - image: ghajduk3/event-catalog:latest
          name: event-catalog
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /event/health/live
              port: server
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /event/health/ready
              port: server
            initialDelaySeconds: 120
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: event-catalog
spec:
#  Changed to ClusterIP because we are using Ingress
  type: ClusterIP

  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: event-catalog